3. UI design
loqit/ToDo pull request #2
Opened 2021-04-10 19:46 UTC by loqit

2021-04-25 09:36 UTC, gmltA requested changes

2021-04-25 09:36 UTC, gmltA commented on css/nav-bar.css
> +#add-task-form {
It's better to use classes, than IDs.

2021-04-25 09:36 UTC, gmltA commented on html/boards.html
> +            <div><h1>ToDo</h1></div>
Why do you need `div` here?

2021-04-26 14:09 UTC, gmltA reviewed
Okay. Is <kbd>8</kbd> enough?

2021-04-26 14:12 UTC, loqit commented
> Okay. Is 8 enough?

Yes

2021-04-26 18:38 UTC, gmltA approved these changes

2021-04-26 18:39 UTC, merged