Final
loqit/ToDo pull request #4
Opened 2021-05-05 21:23 UTC by loqit

2021-05-06 17:26 UTC, gmltA requested changes
Everything's fine.

Can you add a [skeleton](https://material-ui.com/components/skeleton/) for when your boards and items are being loaded from the remote?

2021-05-15 19:34 UTC, gmltA requested changes

2021-05-15 19:34 UTC, gmltA commented on public/js/boards.js
> +    setTimeout(function(){ removeElementsByClass('board-skeleton') }, 300);
Uhm you should display it while your data is being loaded. Not for some arbitrary period.

2021-05-18 19:24 UTC, gmltA approved these changes
Good. That's a <kbd>9</kbd>. And the resulting mark will be <kbd>9</kbd> too.

2021-05-18 19:26 UTC, loqit commented
> Good. That's a <kbd>9</kbd>. And the resulting mark will be <kbd>9</kbd> too.

Thanks

2021-05-18 19:26 UTC, merged